# Barvian.me
# ==========

name: Maxwell Barvian
title: Digital product designer
location: Chicago, IL

url: http://barvian.me
keywords:
  - designer
  - web designer
  - ios designer
  - chicago web designer
  - front-end development
  - web design

email: max@barvian.me
social:
  -
    name: Dribbble
    url: https://dribbble.com/barvian
  -
    name: Github
    url: https://github.com/barvian
  -
    name: LinkedIn
    url: https://www.linkedin.com/in/maxwell-barvian-8bb1b610a


# Collections
# -----------

collections:
  works:
    output: true
    permalink: /:path/


# Build settings
# --------------

exclude:
  - node_modules
  - npm-debug*
  - package.json
  - CNAME
  - bower.json
  - README.md

permalink: pretty
defaults:
  -
    scope:
      path: '' # all files
    values:
      layout: 'default'


# Writing
# -------

markdown: kramdown
kramdown:
  auto_ids: false
