# Barvian.me
# ==========

url: http://barvian.me
keywords:
  - designer
  - web designer
  - ios designer
  - san diego web designer
  - front-end development
  - web design

email: max@barvian.me
external:
  medium:
    name: Medium
    sprite: medium
    url: https://medium.com/@barvian
  dribbble:
    name: Dribbble
    sprite: dribbble
    url: https://dribbble.com/barvian
  github:
    name: Github
    sprite: github
    url: https://github.com/barvian
  linkedin:
    name: LinkedIn
    sprite: linkedin
    url: https://www.linkedin.com/in/maxwell-barvian-8bb1b610a

social:
  letterboxd: https://letterboxd.com/mbarvian/


# Collections
# -----------

collections:
  works:
    output: true
    permalink: /:path/


# Build settings
# --------------

exclude:
  - CNAME
  - README.md

permalink: pretty

sass:
  style: compressed
