# Barvian.me
# ==========

tagline: Former software designer currently researching screens.

url: http://barvian.me
keywords:
  - designer
  - web designer
  - ios designer
  - san diego web designer
  - front-end development
  - web design

email: max@barvian.me
resume: https://www.dropbox.com/s/x2asbomk564h2dj/maxwell_barvian_designer_may2017.pdf?dl=0
external:
  medium:
    name: Medium
    url: https://medium.com/@barvian
  dribbble:
    name: Dribbble
    url: https://dribbble.com/barvian
  github:
    name: Github
    url: https://github.com/barvian
  linkedin:
    name: LinkedIn
    url: https://www.linkedin.com/in/maxwell-barvian-8bb1b610a

social:
  letterboxd: https://letterboxd.com/mbarvian/


# Build settings
# --------------

exclude:
  - CNAME
  - README.md

permalink: pretty
