# Barvian.me
# ==========

name: Maxwell Barvian
title: Digital product designer
role: Designer
location: Chicago, IL

url: http://barvian.me
keywords:
  - designer
  - web designer
  - ios designer
  - chicago web designer
  - front-end development
  - web design

email: max@barvian.me
external:
  -
    name: Dribbble
    sprite: dribbble
    url: https://dribbble.com/barvian
  -
    name: Github
    sprite: github
    url: https://github.com/barvian
  -
    name: LinkedIn
    sprite: linkedin
    url: https://www.linkedin.com/in/maxwell-barvian-8bb1b610a

available: true

social:
  letterboxd: https://letterboxd.com/mbarvian/


# Collections
# -----------

collections:
  works:
    output: true
    permalink: /:path/


# Build settings
# --------------

exclude:
  - node_modules
  - npm-debug*
  - package.json
  - CNAME
  - bower.json
  - README.md

destination: _build

permalink: pretty
defaults:
  -
    scope:
      path: '' # all files
    values:
      layout: 'page'
  -
    scope:
      path: ''
      type: 'works'
    values:
      layout: 'work'
      class: 'work'

sass:
  sass_dir: assets/_sass
  style: compressed

# Writing
# -------

markdown: kramdown
kramdown:
  auto_ids: false
