environment: production

# Barvian.me
# ==========

name: Maxwell Barvian
title: Digital product designer
url: http://barvian.me
baseurl: ''
keywords:
  - designer
  - web designer
  - ios designer
  - chicago web designer
  - front-end development
  - web design

email: max@barvian.me
social:
  dribbble: https://dribbble.com/barvian
  github: https://github.com/barvian
  linkedin: https://www.linkedin.com/in/maxwell-barvian-8bb1b610a

location: Chicago, IL


# Sources
# -------

includes_dir: .


# Collections
# -----------

collections:
  works:
    output: true
    permalink: /:path/


# Build settings
# --------------

exclude:
  - node_modules
  - npm-debug*
  - package.json
  - CNAME
  - bower.json
  - README.md

permalink: pretty
defaults:
  -
    scope:
      path: '' # all files
    values:
      layout: 'default'


# Writing
# -------

markdown: kramdown
kramdown:
  auto_ids: false
