# Barvian.me
# ==========

tagline: Software designer/developer with a passion for wellness.
location: Suburban Chicago, IL

url: http://barvian.me
keywords:
  - designer
  - web designer
  - ios designer
  - san diego web designer
  - front-end development
  - web design

email: max@barvian.me
resume: https://www.dropbox.com/s/xj742g46om0cxef/maxwell_barvian_resume.pdf?dl=0
external:
  # medium:
  #   name: Medium
  #   url: https://medium.com/@barvian
  linkedin:
    name: LinkedIn
    url: https://www.linkedin.com/in/maxwell-barvian-8bb1b610a
  dribbble:
    name: Dribbble
    url: https://dribbble.com/barvian
  github:
    name: Github
    url: https://github.com/barvian
 
social:
  letterboxd: https://letterboxd.com/mbarvian/


# Build settings
# --------------

exclude:
  - CNAME
  - README.md

permalink: pretty
